name: ttyd
on:
  workflow_dispatch:
    # push:
    #   paths: .github/workflows/code-server.yaml
    inputs:
      install_dufs:
        description: "Install dufs"
        required: true
        default: false
        type: boolean
      install_fresh:
        description: "Install fresh"
        required: true
        default: false
        type: boolean
      install_zig:
        description: "Install zig"
        required: true
        default: false
        type: boolean
      install_helix:
        description: "Install helix"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install cloudflared
        run: |
          VERSION=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/cloudflare/cloudflared/releases | jq -r .[0].tag_name)
          echo "Downloading cloudflared ${VERSION}"
          URL=https://github.com/cloudflare/cloudflared/releases/download/${VERSION}/cloudflared-linux-amd64
          curl -LkSs "${URL}" > cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin
          cloudflared --version

      - name: Install ttyd
        run: |
          VERSION=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/zongou/ttyd/releases | jq -r .[0].tag_name)
          echo "Downloading ttyd ${VERSION}"
          ARCH=$(uname -m)
          URL=https://github.com/zongou/ttyd/releases/download/${VERSION}/ttyd.${ARCH}
          curl -LkSs "${URL}" > ttyd
          chmod +x ttyd
          sudo mv ttyd /usr/local/bin
          ttyd --version
      
      - name: Install dufs
        if: ${{ inputs.install_dufs }}
        run: |
          VERSION=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/sigoden/dufs/releases | jq -r .[0].tag_name)
          echo "Downloading dufs ${VERSION}"
          ARCH=$(uname -m)
          URL=https://github.com/sigoden/dufs/releases/download/${VERSION}/dufs-${VERSION}-${ARCH}-unknown-linux-musl.tar.gz
          curl -L ${URL} | gzip -d | tar -C /usr/local/bin -x
          dufs --version
      
      - name: Install fresh-editor
        if: ${{ inputs.install_fresh }}
        run: |
          VERSION=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/sinelaw/fresh/releases | jq -r .[0].tag_name)
          echo "Downloading fresh-editor ${VERSION}"
          ARCH=$(uname -m)
          URL=https://github.com/sinelaw/fresh/releases/download/v0.4.6/fresh-editor-${ARCH}-unknown-linux-musl.tar.gz
          curl -L ${URL} | gzip -d | tar -C /usr/local/bin --strip-components=1 -x --wildcards "*/fresh"
          fresh --version

      - name: Setup Zig
        if: ${{ inputs.install_zig }}
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.16.0
          cache: true
      
      - name: Install helix editor
        if: ${{ inputs.install_helix }}
        run: |
          VERSION=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/helix-editor/helix/releases | jq -r .[0].tag_name)
          echo "Downloading helix editor ${VERSION}"
          ARCH=$(uname -m)
          URL=https://github.com/helix-editor/helix/releases/download/${VERSION}/helix-${VERSION}-${ARCH}-linux.tar.xz
          curl -L ${URL} | xz -d | tar -C /usr/local/bin --strip-components=1 -x --wildcards "*/hx"
          ln -snf /opt/helix-${VERSION}-${ARCH}-linux/hx /usr/local/bin/hx
          hx --version

      - name: Start ttyd
        run: |
          ttyd -t enableZmodem=true -t enableTrzsz=true -t enableSixel=true --writable bash -l &
          cloudflared tunnel --url localhost:7681
